language: python
matrix:
    include:
        - os: linux
          python: 2.7
        - os: linux
          python: 3.3
        - os: linux
          python: 3.4
        - os: linux
          python: 3.5
        - os: osx
          language: generic
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; sudo apt-get install -y alsa-utils festival flite espeak file libttspico-utils mbrola-en1; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python; brew link --overwrite python ; python --version; fi
install:
  - pip install coveralls coverage
  - pip install .
script:
  - coverage run --branch --source=talkey setup.py -q test
after_success: 
  - coveralls
