language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y alsa-utils festival flite espeak
install:
  - pip install coveralls 
  - pip install .
script:
  - coverage run --branch --source=configy setup.py -q test
after_success: 
  - coveralls
