language: python
os:
  - linux
  - osx
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get install -y alsa-utils festival flite espeak file libttspico-utils mbrola-en1; fi
install:
  - pip install coveralls coverage
  - pip install .
script:
  - coverage run --branch --source=talkey setup.py -q test
after_success: 
  - coveralls
